import type { Metadata } from 'next';
import './globals.css';
import { Noto_Sans } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Top app',
  description: 'Generated by create next app',
};

export const noto = Noto_Sans({
  variable: '--font-noto-sans',
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={noto.className}>
        {children}
      </body>
    </html>
  );
}
