import type { Metadata } from 'next';
import './globals.css';
import { Noto_Sans } from 'next/font/google';
import { Header } from '@/components/Header/Header';
import { Footer } from '@/components/Footer/Footer';
import { SideBar } from '@/components/SideBar/SideBar';
import cn from 'classnames';

export const metadata: Metadata = {
  title: 'Top app',
  description: 'Generated by create next app',
};

export const noto = Noto_Sans({
  variable: '--font-noto-sans',
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={cn(noto.className, 'wrapper')}>
        <Header className='header'/>
          <SideBar className='sidebar'/>
          <div className='body'>
            {children}
          </div>
        <Footer className='footer'/>
      </body>
    </html>
  );
}
